<?php
    $array=array(
        "URL_RELATIVA"=>""
    );
    $archivos=$Archivos->Explorador($array);
    /*
    $array=array(
        "URL_RELATIVA"=>""
    );
    $archivos=$Archivos->Explorar($array);
    $array=array();
    $Archivos->BarraExplorador($array);
    $array=array(
        "class"=>array(
            "Contenedor"=>'ContenidoCarpeta'
        ),
        "Archivos"=>$archivos
    );
    $Archivos->viewExplorar($array);
    */
?>